name: Daily Discord Update

on:
  schedule:
    - cron: '15 23 * * *' # Ajaa automaattisesti klo 1 yöllä UTC
  workflow_dispatch: # Mahdollistaa manuaalisen ajon

permissions:
  contents: write

env:
  # Vaimentaa mahdollisen Node-varoitusviestin
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # Päivitetty uuteen versioon!

    - name: Install FFMPEG
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Install yt-dlp
      run: sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && sudo chmod a+rx /usr/local/bin/yt-dlp
        
    - name: Install node dependencies
      run: npm install discord.js dotenv basic-ftp

    - name: Run data fetch script
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        CHANNEL_ID_1: ${{ secrets.CHANNEL_ID_1 }}
        CHANNEL_ID_2: ${{ secrets.CHANNEL_ID_2 }}
        CHANNEL_ID_3: ${{ secrets.CHANNEL_ID_3 }}
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASS: ${{ secrets.FTP_PASS }}
        FTP_DIR: ${{ secrets.FTP_DIR }}
        FTP_WEB_URL: ${{ secrets.FTP_WEB_URL }}
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      run: node index.js

    - name: Commit and Push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'bot@actions.github.com'
        git add top20_songs.json
        
        # Tehdään commit. Jos data ei muuttunut, ei kaadeta ajoa.
        git commit -m "Automaattinen listan päivitys" || echo "Ei uutta commitattavaa"
        
        # Haetaan uudet muutokset reposta, mutta jos tulee konflikti JSONin kanssa, 
        # pidetään botin juuri tekemä versio (-X ours)
        git pull --rebase -X ours origin main
        
        # Pusketaan muutokset takaisin GitHubiin
        git push origin main
